//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventes
    {
        public int Id { get; set; }
        public int couleurid { get; set; }
        public int marqueid { get; set; }
        public double valeur { get; set; }
        public System.DateTime date { get; set; }
    }
}
